SELECT ID,
    CASE 
        WHEN RANK() OVER (ORDER BY SIZE_OF_COLONY) <= COUNT(*) OVER () / 4 THEN "LOW"
        WHEN RANK() OVER (ORDER BY SIZE_OF_COLONY) > COUNT(*) OVER () / 4
             AND RANK() OVER (ORDER BY SIZE_OF_COLONY) <= COUNT(*) OVER () / 2 THEN "MEDIUM"
        WHEN RANK() OVER (ORDER BY SIZE_OF_COLONY) > COUNT(*) OVER () / 2
             AND RANK() OVER (ORDER BY SIZE_OF_COLONY) <= COUNT(*) OVER () * 3 / 4 THEN "HIGH"
        ELSE "CRITICAL"
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;