WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS H
    UNION ALL
    (
        SELECT H + 1
        FROM HOUR_TABLE
        WHERE H < 23
    )
)
SELECT HT.H AS HOUR, COUNT(CASE WHEN ANIMAL_ID IS NOT NULL THEN 1 END) AS COUNT
FROM ANIMAL_OUTS AO
RIGHT JOIN HOUR_TABLE HT
ON HOUR(AO.DATETIME) = HT.H
GROUP BY HT.H
ORDER BY HT.H