-- 코드를 작성해주세요
SELECT DISTINCT B.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A
INNER JOIN
ITEM_TREE AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY='RARE'
)
ORDER BY ITEM_ID DESC
;

# SELECT * FROM ITEM_INFO
# INNER JOIN
# ITEM_TREE
# WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
# ;